linkar_homepage:
    path:     /exemple
    defaults: { _controller: LinkarBundle:Membre:exemple }
stat:
    path:     /stat
    defaults: { _controller: LinkarBundle:Membre:index}
compte:
    path:     /compte
    defaults: { _controller: LinkarBundle:Membre:index2}
upload:
    path:     /upload
    defaults: { _controller: LinkarBundle:Membre:upload}
verificationCompte:
    path:     /verifierCompte
    defaults: { _controller: LinkarBundle:Membre:verifierCompte}
changePassword:
    path:     /changePassword
    defaults: { _controller: LinkarBundle:Membre:changePassword}
personnelInfo:
    path:     /personnelInfo
    defaults: { _controller: LinkarBundle:Membre:personnel}





