conversation:
    path:     /conversation
    defaults: { _controller: MessageBundle:Message:getConversation}
list:
    path:     /list
    defaults: { _controller: MessageBundle:Message:getListMembers}
testsss:
    path:     /liste
    defaults: { _controller: MessageBundle:Message:index}
inbox:
    path:     /inbox
    defaults: { _controller: MessageBundle:Message:inBox}
