conversation:
    path:     /conversation
    defaults: { _controller: MessageBundle:Message:getConversation}
list:
    path:     /list
    defaults: { _controller: MessageBundle:Message:getListMembers}
