upload:
    resource: "@UploadBundle/Resources/config/routing.yml"
    prefix:   /

email:
    resource: "@EmailBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

notification:
    resource: "@NotificationBundle/Resources/config/routing.yml"
    prefix:   /

message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix:   /

stat:
    resource: "@StatBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

linkar:
    resource: "@LinkarBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
upload:
    resource: "@UploadBundle/Resources/config/routing.yml"
    prefix:   /

email:
    resource: "@EmailBundle/Resources/config/routing.yml"

