# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
     fos_user.doctrine_registry:
         alias: doctrine
     redirect.after.login:
         class: UserBundle\Redirection\AfterLoginRedirection
         arguments: ["@router"]
     app.form.registration:
            class: App\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }
