<?php

namespace LinkarBundle\Repository;

/**
 * VoitureModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoitureModelRepository extends \Doctrine\ORM\EntityRepository
{
}
