stat_homepage:
    path:     /
    defaults: { _controller: StatBundle:Default:index }
annoucneStatestic:
    path:     /admin/announceStat
    defaults: { _controller: StatBundle:Graphe:AnnounceStat }
userStatestic:
    path:     /admin/userStat
    defaults: { _controller: StatBundle:Graphe:UserStat }





