stat_homepage:
    path:     /
    defaults: { _controller: StatBundle:Default:index }
annoucneStatestic:
    path:     /announceStat
    defaults: { _controller: StatBundle:Graphe:AnnounceStat }
userStatestic:
    path:     /userStat
    defaults: { _controller: StatBundle:Graphe:UserStat }





